# Generated by Django 4.2.29 on 2026-03-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel', 'verbose_name_plural': 'Hoteles'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='roombooking',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de usuario', 'verbose_name_plural': 'Perfiles de usuario'},
        ),
    ]
