# Generated by Django 4.2.29 on 2026-03-23 19:37

from django.db import migrations


def migrate_core_rooms_to_bookings(apps, schema_editor):
    CoreRoom = apps.get_model('core', 'Room')
    CoreRoomBooking = apps.get_model('core', 'RoomBooking')
    BookingRoom = apps.get_model('bookings', 'Room')
    BookingRoomBooking = apps.get_model('bookings', 'RoomBooking')

    room_id_map = {}

    for core_room in CoreRoom.objects.all():
        booking_room, created = BookingRoom.objects.get_or_create(
            hotel_id=core_room.hotel_id,
            room_number=core_room.room_number,
            defaults={
                'room_type': core_room.room_type,
                'capacity': core_room.capacity,
                'price_per_night': core_room.price_per_night,
                'is_active': core_room.is_active,
            },
        )

        if created:
            BookingRoom.objects.filter(pk=booking_room.pk).update(
                created_at=core_room.created_at,
                updated_at=core_room.updated_at,
            )

        room_id_map[core_room.pk] = booking_room.pk

    for core_booking in CoreRoomBooking.objects.all():
        booking_room_id = room_id_map.get(core_booking.room_id)
        if not booking_room_id:
            continue

        booking, created = BookingRoomBooking.objects.get_or_create(
            user_id=core_booking.user_id,
            room_id=booking_room_id,
            start_date=core_booking.start_date,
            end_date=core_booking.end_date,
            defaults={
                'recurrence': core_booking.recurrence,
            },
        )

        if created:
            BookingRoomBooking.objects.filter(pk=booking.pk).update(
                created_at=core_booking.created_at,
                updated_at=core_booking.updated_at,
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_room_hotel'),
        ('core', '0002_alter_hotel_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_core_rooms_to_bookings, noop_reverse),
        migrations.RemoveField(
            model_name='roombooking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomBooking',
        ),
    ]
