# Generated by Django 4.2.29 on 2026-03-23 19:49

from django.db import migrations, models
import django.db.models.deletion


def copy_hotel_main_image_to_gallery(apps, schema_editor):
    Hotel = apps.get_model('core', 'Hotel')
    HotelImage = apps.get_model('core', 'HotelImage')

    for hotel in Hotel.objects.exclude(hotel_img='').exclude(hotel_img__isnull=True):
        HotelImage.objects.get_or_create(
            hotel_id=hotel.pk,
            image=hotel.hotel_img,
            defaults={'position': 0},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_roombooking_room_remove_roombooking_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='hotel_images/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.hotel')),
            ],
            options={
                'verbose_name': 'Imagen de hotel',
                'verbose_name_plural': 'Imágenes de hotel',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.RunPython(copy_hotel_main_image_to_gallery, noop_reverse),
    ]
