# Generated by Django 4.2.29 on 2026-03-23 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_hotel_options_alter_room_options_and_more'),
        ('bookings', '0002_alter_room_options_alter_roombooking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.hotel'),
        ),
    ]
