# Generated by Django 4.2.29 on 2026-03-23 19:49

from django.db import migrations, models
import django.db.models.deletion


def copy_room_main_image_to_gallery(apps, schema_editor):
    Room = apps.get_model('bookings', 'Room')
    RoomImage = apps.get_model('bookings', 'RoomImage')

    for room in Room.objects.exclude(room_imgs='').exclude(room_imgs__isnull=True):
        RoomImage.objects.get_or_create(
            room_id=room.pk,
            image=room.room_imgs,
            defaults={'position': 0},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_room_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='room_images/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bookings.room')),
            ],
            options={
                'verbose_name': 'Imagen de habitación',
                'verbose_name_plural': 'Imágenes de habitación',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.RunPython(copy_room_main_image_to_gallery, noop_reverse),
    ]
